spring.application.name=Calendar
server.port=8081
spring.security.oauth2.client.registration.google.client-id= client id hidden
spring.security.oauth2.client.registration.google.client-secret= client sercret hidden
spring.security.oauth2.client.registration.google.redirect-uri=http://35.186.220.230.nip.io/calendar/login/oauth2/code/google
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.scope=openid,profile,email
google.calendar.clientId=your-client-id
google.calendar.clientSecret=your-client-secret
google.calendar.applicationName=Your Calendar App
google.calendar.refreshToken=your-refresh-token
google.calendar.accessToken=your-access-token