spring.application.name=FE
server.port=8080

spring.security.oauth2.client.registration.google.client-id= client id hidden
spring.security.oauth2.client.registration.google.client-secret= client sercret hidden
calendar.service.url=http://35.186.220.230.nip.io
weather.service.url=http://35.186.220.230.nip.io
spring.security.oauth2.client.registration.google.redirect-uri=http://35.186.220.230.nip.io/login/oauth2/code/google
