spring.application.name=Weather
server.port=8082
spring.security.oauth2.client.registration.google.client-id= client id hidden
spring.security.oauth2.client.registration.google.client-secret= client sercret hidden
spring.security.oauth2.client.registration.google.redirect-uri=http://35.186.220.230.nip.io/weather/login/oauth2/code/google
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.scope=openid,profile,email